const ThemesObj = {
    themes: [
      {
        name: 'Casey_Works',
        icon: 'fas fa-user-md',
        background: `#000000`,
        borderColor: '#90EE90',
        altBorderColor: '#212121',
        altBackground: '#2121213C',
        text: '#ffffff',
        iconColor: '#ffffff',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '7px 4px',
        borderStyle: 'groove',
        hfont: `'Megrim', cursive`,
        ffont: `'Ubuntu Mono', monospace`
      },
  
  
      // background: 'black',
      // borderColor: 'white',
      // altBackground: '#212121',
      // altBorderColor: 'white',
      // icon: 'white',
      // text: 'white',
      // borders: true,
      // crazy: false,
      // offset: false,
      // borderRadius: '4px',
      // borderStyle: 'groove',
      // hfont: { value: `'Megrim', cursive`, label: `Megrim`, className: 'megrim' },
      // ffont: { value: `'Nova Mono', monospace`, label: `Nova Mono`, className: 'nova' }
  
      {
        name: 'Bitcoin',
        icon: 'fab fa-bitcoin',
        background: `#fff`,
        borderColor: '#FF9900',
        altBorderColor: '#FF9900',
        altBackground: '#fff',
        text: '#000',
        iconColor: 'red',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '7px 4px',
        borderStyle: 'groove',
        hfont: `'Montserrat', sans-serif`,
        ffont: `'Montserrat', sans-serif`
      },
      {
        name: 'Bubblegum',
        icon: 'fas fa-birthday-cake',
        background: `#FB579A`,
        borderColor: '#2FCB43',
        altBorderColor: '#d2ca79',
        altBackground: '#0F6B81',
        text: '#66A0E4',
        iconColor: "#1A8A5E",
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: "10px 4px",
        borderStyle: 'groove',
        hfont: "'Skranji', cursive",
        ffont: "'Nova Mono', monospace"
      },
      {
        name: 'Superman',
        icon: 'far fa-gem',
        background: `#cde577`,
        borderColor: '#B9F058F8',
        altBorderColor: '#CA78F4',
        altBackground: '#CA78F4',
        text: '#000',
        iconColor: 'red',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '4px',
        borderStyle: 'solid',
        hfont: `'Pangolin', cursive`,
        ffont: `'Pangolin', cursive`
      },
      {
        name: 'Submarine',
        icon: 'fas fa-fighter-jet',
        background: `#cde577`,
        borderColor: '#B9F058F8',
        altBorderColor: '#CA78F4',
        altBackground: '#CA78F4',
        text: '#000',
        iconColor: 'red',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '4px',
        borderStyle: 'solid',
        hfont: `'Pangolin', cursive`,
        ffont: `'Pangolin', cursive`
      },
      {
        name: 'Nightman',
        icon: 'fas fa-bomb',
        background: `#cde577`,
        borderColor: '#B9F058F8',
        altBorderColor: '#CA78F4',
        altBackground: '#CA78F4',
        text: '#000',
        iconColor: 'red',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '4px',
        borderStyle: 'solid',
        hfont: `'Pangolin', cursive`,
        ffont: `'Pangolin', cursive`
      },
      {
        name: 'Terminal',
        icon: 'fas fa-terminal',
        background: `#000`,
        borderColor: '#90EE90',
        altBorderColor: '#90EE90',
        altBackground: '#CA78F4',
        text: '#2121213C',
        iconColor: 'red',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '4px',
        borderStyle: 'solid',
        hfont: `'Pangolin', cursive`,
        ffont: `'Pangolin', cursive`
      },
      {
        name: 'Winter',
        icon: 'far fa-snowflake',
        background: `#000`,
        borderColor: '#90EE90',
        altBorderColor: '#90EE90',
        altBackground: '#CA78F4',
        text: '#2121213C',
        iconColor: 'red',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '4px',
        borderStyle: 'solid',
        hfont: `'Pangolin', cursive`,
        ffont: `'Pangolin', cursive`
      },
  
      {
        name: 'PopLogics',
        icon: 'far fa-star',
        background: `#000`,
        borderColor: '#90EE90',
        altBorderColor: '#90EE90',
        altBackground: '#CA78F4',
        text: '#2121213C',
        iconColor: 'red',
        borders: true,
        offset: false,
        crazy: false,
        borderRadius: '4px',
        borderStyle: 'solid',
        hfont: `'Pangolin', cursive`,
        ffont: `'Pangolin', cursive`
      }
    ]
  }
  
  export default ThemesObj;